{
 "title": "APT Monitoring",
 "description": "Monitoring APT upgrades and outstanding reboots with Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_reboot_required,instance)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Systems Require Reboot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_reboot_required{instance=~'$instance'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security Upgrades Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apt_security_upgrades_pending{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upgrades Pending",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apt_upgrades_pending{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security Upgrades Pending",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "apt_security_upgrades_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upgrades Pending",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "apt_upgrades_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "APT Check",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "node_reboot_required{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "apt_security_upgrades_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "apt_upgrades_pending{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}